### ISSUE TITLE
Invalid input file index: 3. Error! The file .mp4 was not created.

### ISSUE THREAD

**Issue by wanghaisheng** [WyattBlue/auto-editor#219] opened 2021-12-01 17:32 UTC
**What version are you running?** 
(Make sure you've tried the latest version)

**What went wrong**

```
[info] Video metadata is already present


 _ #shorts [hsrV3iHIi78].mp4'; could not find a mapping for mp4
[EmbedSubtitle] Embedding subtitles in "Youtube\[UCCm4EdCTj3hVbDYPAI1FHtA] Sheena Melwani\[20211130] Pizza Or Nothing 🍕 _ #shorts [hsrV3iHIi78].mp4"
Deleting original file Youtube\[UCCm4EdCTj3hVbDYPAI1FHtA] Sheena Melwani\[20211130] Pizza Or Nothing 🍕 _ #shorts [hsrV3iHIi78].en.srt (pass -k to keep)
[Metadata] Adding metadata to "Youtube\[UCCm4EdCTj3hVbDYPAI1FHtA] Sheena Melwani\[20211130] Pizza Or Nothing 🍕 _ #shorts 
[hsrV3iHIi78].mp4"
[EmbedThumbnail] mutagen: Adding thumbnail to "Youtube\[UCCm4EdCTj3hVbDYPAI1FHtA] Sheena Melwani\[20211130] Pizza Or Nothing 🍕 _ #shorts [hsrV3iHIi78].mp4"
[Exec] Executing command: auto-editor  "D:\Download\audio-visual\UCBBj-A2EqL5pNApsLhoeM6w\Youtube\[UCCm4EdCTj3hVbDYPAI1FHtA] Sheena Melwani\[20211130] Pizza Or Nothing 🍕 _ #shorts [hsrV3iHIi78].mp4"
stream 0, timescale not set░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0.1% done ETA 01:25 AM
ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200621
  configuration: --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001c3aaf9e180] stream 0, timescale not set
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\Download\audio-visual\UCBBj-A2EqL5pNApsLhoeM6w\Youtube\[UCCm4EdCTj3hVbDYPAI1FHtA] Sheena Melwani\[20211130] Pizza Or Nothing 🍕 _ #shorts [hsrV3iHIi78].mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    title           : Pizza Or Nothing? 🍕 | #shorts
    artist          : Sheena Melwani
    date            : 20211130
    encoder         : Lavf58.45.100
    comment         : https://www.youtube.com/watch?v=hsrV3iHIi78
  Duration: 00:00:41.88, start: 0.000000, bitrate: 2133 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 1080x1920, 1960 kb/s, SAR 1:1 DAR 9:16, 30.02 fps, 30 tbr, 16k tbn, 16k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 133 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(eng): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)
    Metadata:
      handler_name    : SubtitleHandler
    Stream #0:3: Video: png, rgb24(pc), 1280x720, 90k tbr, 90k tbn, 90k tbc (attached pic)
Stream mapping:
  Stream #0:0 -> #0:0 (vp9 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
Output #0, matroska, to 'pipe:1':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    title           : Pizza Or Nothing? 🍕 | #shorts
    artist          : Sheena Melwani
    date            : 20211130
    comment         : https://www.youtube.com/watch?v=hsrV3iHIi78
    encoder         : Lavf58.45.100
    Stream #0:0(eng): Video: rawvideo (I420 / 0x30323449), yuv420p, 1080x1920 [SAR 1:1 DAR 9:16], q=2-31, 746496 kb/s, 30 
fps, 1k tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.91.100 rawvideo
frame= 1213 fps=115 q=-0.0 Lsize= 3684520kB time=00:00:40.40 bitrate=747100.1kbits/s speed=3.84x     AM
video:3684488kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000890%
Invalid input file index: 3.
Error! The file D:\Download\audio-visual\UCBBj-A2EqL5pNApsLhoeM6w\Youtube\[UCCm4EdCTj3hVbDYPAI1FHtA] Sheena Melwani\[20211130] Pizza Or Nothing 🍕 _ #shorts [hsrV3iHIi78]_ALTERED.mp4 was not created.

Something went wrong!
Create a bug report at:
  https://github.com/WyattBlue/auto-editor/issues/
ERROR: Command returned error code 1
```

**Describe what went wrong**

```
Paste the terminal output here.
```

**What conditions must be met for it to be wrong** 

**Does the example video work? (if applicable)**

**What's your platform? (if applicable)**
Run: `auto-editor --debug`

```
$ auto-editor --debug
Python Version: 3.8.5 64-bit
Platform: Windows 10
Config File path: D:\Program Files\anaconda3\Lib\site-packages\auto_editor\config.txt
FFmpeg path: D:\Program Files\anaconda3\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
FFmpeg version: 4.3
Auto-Editor version 21w46b
```

**What properties your input file(s)? (if applicable)**
You can use  `aeinfo ./path/to/video.mp4` or `ffmpeg -hide_banner -i ./path/to/video.mp4` to get standard info.

```
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    title           : Hips Don’t Lie #shorts
    artist          : NOW UNITED
    date            : 20211130
    encoder         : Lavf58.45.100
    comment         : https://www.youtube.com/watch?v=YVlGkukGs3M
    description     : 🔥🔥🔥 #shorts #shakira #hipsdontlie
                    :
                    : Follow NOW UNITED for more updates:
                    : Instagram: http://www.instagram.com/nowunited​​​​
                    : Facebook: http://www.facebook.com/NowUnited​​​​
                    : Twitter: http://www.twitter.com/nowunitedmusic​​​​
                    :
                    : NOW UNITED's official website:
                    : https://www.nowunited.com/
  Duration: 00:00:15.12, start: 0.000000, bitrate: 2069 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 720x1280, 1499 kb/s, SAR 1:1 DAR 9:16, 30.07 fps, 30 tbr, 16k tbn, 16k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 106 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2: Video: png, rgb24(pc), 1280x720, 90k tbr, 90k tbn, 90k tbc (attached pic)
```

**Comment by WyattBlue** [comment] 2021-12-02 00:30
I have encountered this error too. The cause is that there is an additional video track (the embedded thumbnail) that auto-editor recognizes, but doesn't properly account for. Auto-Editor sends an FFmpeg command that uses a map selector that doesn't exist, and that causes the error that you see.

I have fixed this bug in the new version, so I am closing this issue.

**Closed by WyattBlue** 2021-12-02 00:30 UTC
Labels: bug
