### ISSUE TITLE
Audio out of sync on HD videos

### ISSUE THREAD

**Issue by petermg** [WyattBlue/auto-editor#268] opened 2022-04-25 18:20 UTC
### What's your platform?

```shell
Python Version: 3.9.6 64-bit
Platform: Windows 10 amd64
FFmpeg Version: 2022-04-18-git-d5687236ab-full_build-www.gyan.dev
FFmpeg Path: C:\Users\pgomb\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 22w16a

Same issue with 
Python Version: 3.9.6 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-105325-g7512293cf9
FFmpeg Path: C:\Users\pgomb\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 22w16a
```

### Bug description

When running auto-editor on an HD video file around 3 hours in length, the sound gets out of sync. If I use it on a low res video, this doesn't happen. These were just some random 3 hour long interview videos I found to test this on:
This is the HD video it got out of sync on:https://youtu.be/ycPr5-27vSI
These are the videos that are SD and audio did NOT lose sync on these:
https://youtu.be/g1Wganu0nZs
https://youtu.be/cY-5-IIAVa8

### What command did you use

```shell
auto-editor 3HourTest.mp4 (this was for the HD video) Same syntax for the low res videos.
```

### What properties does your input video have?

```shell
For the HD video that gets out of sync:
file: 3HourTest.mp4
 - video tracks: 1
   - Track #0
     - codec: h264
     - pix_fmt: yuv420p
     - fps: 29.97
     - resolution: 1280x720 (16:9)
     - bitrate: 1230 kb/s
     - lang: und
 - audio tracks: 1
   - Track #0
     - codec: aac
     - samplerate: 44100
     - bitrate: 128 kb/s
     - lang: und
 - container:
   - duration: 02:37:02.33
   - bitrate: 1361 kb/s

one of the low res videos that did NOT get out of sync:
file: https-youtu-be-cY-5-IIAVa8.mp4
 - video tracks: 1
   - Track #0
     - codec: h264
     - pix_fmt: yuv420p
     - fps: 29.97
     - resolution: 640x360 (16:9)
     - bitrate: 365 kb/s
     - lang: und
 - audio tracks: 1
   - Track #0
     - codec: aac
     - samplerate: 44100
     - bitrate: 95 kb/s
     - lang: und
 - container:
   - duration: 02:59:48.18
   - bitrate: 463 kb/s
```

**Comment by WyattBlue** [comment] 2022-04-25 20:36
Duplicate of #261 and I'm pretty sure the cause isn't that the video's HD, but PyAV is calculating the incorrect time.

**Closed by WyattBlue** 2022-04-25 20:36 UTC
Labels: desync
