### ISSUE TITLE
Large output file, choppy/jump audio and errors reported by VLC

### ISSUE THREAD

**Issue by bdutta** [WyattBlue/auto-editor#190] opened 2021-06-13 07:16 UTC
Using the absolute latest version of auto-editor, I have been trying to use it to just speed-up/skip the silent parts of a recorded webinar. The webinar was recorded using CISCO Webex recording facility and I cropped the video (frame-size reduction, not length edit) to mask out some proprietary information about attendees etc. This video called `Day4_VJonly.mkv` was what auto-editor was invoked on. _Note that I applied auto-editor without any options i.e. all defaults, so expecting the somewhat aggressive audio based silence removal._

**What went wrong**
Noticed several things which seem odd:

1. First, it seems very odd that the filesize would grow so humongously after compressing/compacting it.
```
-rw-rw-r-- 1 bdutta bdutta 1153907518 Jun 13 12:23 Day4_VJonly_ALTERED.mkv
-rw-rw-r-- 1 bdutta bdutta  150221737 Jun 12 19:29 Day4_VJonly.mkv

```
2. Noticed the the resulting ALTERED file codec/characteristics are different from original, with the summary being:
```
ALTERED
    Stream 0
        Codec: MPEG-4 (mp4v)
        Res: 1600x900
        Frame rate: 12
    Stream 1
        Codec: Vorbis
        Sample Rate: 44100 Hz
        Bits per sample: 32
        Bitrate: 112 kb/s

ORIG
    Stream 0
        Codec: H264 - MPEG-4 AVC (part 10)(avc 1)
        Res: 1600x900
        Frame rate: 12
    Stream 1
        Codec: MPEG Audio layer 1/2 (mpga)
        Sample rate: 44100 Hz
        Bits per sample: 32
        Bitrate: 32 kb/s
```
3. The audio sounds a bit stuttery or jumpy, and it seems parts of intelligible (but low amplitude) voice has been chopped off as well. I won't say this is terrible, but noticeable where a sentence is dropped before it meaningfully end, and audio jumps ahead.

```
Input #0, matroska,webm, from 'Day4_VJonly.mkv':
  Metadata:
    title           : TAS_DeveloperTraining_Day4
    ENCODER         : Lavf58.29.100
  Duration: 03:05:55.17, start: -0.156000, bitrate: 107 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1600x900 [SAR 1:1 DAR 16:9], 12 fps, 12 tbr, 1k tbn, 24 tbc (default)
    Metadata:
      title           : Video
      BPS-eng         : 176302
      DURATION-eng    : 03:37:57.416000000
      NUMBER_OF_FRAMES-eng: 156929
      NUMBER_OF_BYTES-eng: 288197828
      _STATISTICS_WRITING_APP-eng: mkvmerge v53.0.0 ('Fool's Gold') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-05-10 13:54:04
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      ENCODER         : Lavc58.54.100 libx264
      DURATION        : 03:05:55.166000000
    Stream #0:1(eng): Audio: mp3, 44100 Hz, stereo, fltp, 32 kb/s (default)
    Metadata:
      title           : Audio
      BPS-eng         : 57051
      DURATION-eng    : 03:37:57.359000000
      NUMBER_OF_FRAMES-eng: 500609
      NUMBER_OF_BYTES-eng: 93259893
      _STATISTICS_WRITING_APP-eng: mkvmerge v53.0.0 ('Fool's Gold') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-05-10 13:54:04
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 03:05:54.850000000
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
Output #0, matroska, to 'pipe:1':
  Metadata:
    title           : TAS_DeveloperTraining_Day4
    encoder         : Lavf58.29.100
    Stream #0:0(eng): Video: rawvideo (I420 / 0x30323449), yuv420p, 1600x900 [SAR 1:1 DAR 16:9], q=2-31, 207360 kb/s, 12 fps, 1k tbn, 12 tbc (default)
    Metadata:
      title           : Video
      BPS-eng         : 176302
      DURATION-eng    : 03:37:57.416000000
      NUMBER_OF_FRAMES-eng: 156929
      NUMBER_OF_BYTES-eng: 288197828
      _STATISTICS_WRITING_APP-eng: mkvmerge v53.0.0 ('Fool's Gold') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-05-10 13:54:04
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 03:05:55.166000000
      encoder         : Lavc58.54.100 rawvideo
Input #0, rawvideo, from 'pipe:':░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0.0% done ETA 12:38 PM                
  Duration: N/A, start: 0.000000, bitrate: 207360 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1600x900, 207360 kb/s, 12 tbr, 12 tbn, 12 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> mpeg4 (native))
Output #0, mp4, to '/tmp/tmpgim3pnr2/spedup.mp4':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 1600x900, q=2-31, 200 kb/s, 12 fps, 12288 tbn, 12 tbc
    Metadata:
      encoder         : Lavc58.54.100 mpeg4
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
Traceback (most recent call last):░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 6.4% done ETA 12:49 PM                
  File "/home/bdutta/.local/lib/python3.8/site-packages/auto_editor/renderVideo.py", line 75, in read
[mp4 @ 0x558ae1c84240] Starting second pass: moving the moov atom to the beginning of the file
    return self._fh.read(buf_size)
KeyboardInterrupt
Exception ignored in: 'av.container.pyio.pyio_read_gil'
Traceback (most recent call last):
  File "/home/bdutta/.local/lib/python3.8/site-packages/auto_editor/renderVideo.py", line 75, in read
    return self._fh.read(buf_size)
KeyboardInterrupt: 
frame= 8571 fps=209 q=-0.0 Lsize=18079688kB time=00:11:54.16 bitrate=207386.5kbits/s dup=2 drop=0 speed=17.5x    
video:18079453kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.001298%
Exiting normally, received signal 2.
frame= 5957 fps=146 q=1.0 Lsize=  110298kB time=00:08:16.33 bitrate=1820.5kbits/s speed=12.1x    
video:110271kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.024118%
Exiting normally, received signal 2.
['ffmpeg', '-hide_banner', '-y', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-pix_fmt', 'yuv420p', '-s', '1600*900', '-framerate', '12.0', '-i', '-', '-pix_fmt', 'yuv420p', '-vcodec', 'mpeg4', '-qscale:v', '1', '-movflags', '+faststart', '-strict', '-2', '/tmp/tmpgim3pnr2/spedup.mp4']
Error! Broken Pipe Error!                                                                                              
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, bitrate: 207360 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1600x900, 207360 kb/s, 12 tbr, 12 tbn, 12 tbc
/tmp/tmpgim3pnr2/spedup.mp4: No such file or directory
```

**Does the example video work? (if applicable)**
Not quite sure what this means, but I've tried it on a short 30 second video I recorded myself with periods of silence and fairly uniform audio, and auto-editor seemed to work quite well on it.

**What does the program output when `--debug` or `--show_ffmpeg_debug` is appended to your command/use case**

```
'ffmpeg', '-y', '-i', 'Day4_VJonly.mkv', '-hide_banner', '-map', '0:a:0', '-ac', '2', '-ar', '44100', '/tmp/tmpgim3pnr2/0.wav', '-map', '0:v:0', '-vf', 'vfrdet', '-f', 'null', '-']

```

**What's your platform? (if applicable)**

```
Python Version: 3.8.5 64-bit
Platform: Linux 5.11.0-18.1-liquorix-amd64
Config File path: /home/bdutta/.local/lib/python3.8/site-packages/auto_editor/config.txt
FFmpeg path: ffmpeg
FFmpeg version: 4.2.4-1ubuntu0.1
Auto-Editor version 21w22a

```

**What's your input? (if applicable)**

```
file: Day4_VJonly.mkv
 - fps: 12
 - duration: 03:05:55.17
 - resolution: 1600x900 (16:9)
 - video codec: h264
 - video bitrate: None
 - audio tracks: 1
   - Track #0
     - codec: mp3
     - samplerate: 44100
     - bitrate: 32 kb/s
```

**Comment by igavronski** [comment] 2021-06-13 17:09
Hi,
Strikes me your bitrate as 44100. Most video files are encoded with 48000 audio. Can you reproduce the problem with a video with 48000 audio?

**Comment by WyattBlue** [comment] 2021-07-09 23:17
Large output file: not an issue
choppy audio: can't confirm
errors reported by VLC: ¯\\_( \|\_\| )\_/¯

Closing because of staleness and lack of focus.

**Closed by WyattBlue** 2021-07-09 23:17 UTC
Labels: bug
