### ISSUE TITLE
Youtube Downloading Does not work.

### ISSUE THREAD

**Issue by 03172008** [WyattBlue/auto-editor#132] opened 2021-01-28 17:54 UTC
(Make sure you're using the latest version) ✔

Downloading a youtube video resulted in `TypeError: stat: path should be string, bytes, os.PathLike or integer, not FFmpeg`

```
auto-editor https://www.youtube.com/watch?v=52ZlXsFJULI --edit_based_on audio_or_motion
Traceback (most recent call last):░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% done ETA 12:49 PM
  File "c:\users\me\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\me\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
    import platform
  File "c:\users\me\appdata\local\programs\python\python39\lib\site-packages\auto_editor\__main__.py", line 354, in main
    inputList = validInput(args.input, ffmpeg, log)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\validateInput.py", line 90, in validInput
    ydl.download([myInput])
  File "c:\users\me\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2055, in download
    res = self.extract_info(
  File "c:\users\me\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "c:\users\me\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\me\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 838, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\me\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 872, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "c:\users\me\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 1679, in process_video_result
    self.process_info(new_info)
  File "c:\users\me\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 1907, in process_info
    merger = FFmpegMergerPP(self)
  File "c:\users\me\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 57, in __init__
    self._determine_executables()
  File "c:\users\me\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 102, in _determine_executables
    if not os.path.exists(location):
  File "c:\users\me\appdata\local\programs\python\python39\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not FFmpeg
```

MP4's and MKV's work perfectly, not youtube links

**What does the program output when `--debug` is appended to your command/use case**

```
C:\Users\SHREE>auto-editor https://www.youtube.com/watch?v=52ZlXsFJULI --edit_based_on audio_or_motion --debug

   - Temp Directory: C:\Users\SHREE\AppData\Local\Temp\tmp182ydnie
Traceback (most recent call last):░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% done ETA 12:54 PM
  File "c:\users\shree\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\shree\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\SHREE\AppData\Local\Programs\Python\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
    import platform
  File "c:\users\shree\appdata\local\programs\python\python39\lib\site-packages\auto_editor\__main__.py", line 354, in main
    inputList = validInput(args.input, ffmpeg, log)
  File "C:\Users\SHREE\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\validateInput.py", line 90, in validInput
    ydl.download([myInput])
  File "c:\users\shree\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2055, in download
    res = self.extract_info(
  File "c:\users\shree\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "c:\users\shree\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\shree\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 838, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\shree\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 872, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "c:\users\shree\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 1679, in process_video_result
    self.process_info(new_info)
  File "c:\users\shree\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 1907, in process_info
    merger = FFmpegMergerPP(self)
  File "c:\users\shree\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 57, in __init__
    self._determine_executables()
  File "c:\users\shree\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 102, in _determine_executables
    if not os.path.exists(location):
  File "c:\users\shree\appdata\local\programs\python\python39\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not FFmpeg
```

**What's your platform? (if applicable)**
Windows 10
```
output here, run: `auto-editor --debug` if possible.
```

**What's your input? (if applicable)**

```
output here, run: `auto-editor info path/to/video
```

**Comment by WyattBlue** [comment] 2021-01-29 02:30
Thanks @03172008 for the report.

I was able to replicate the error on my machine and fix it.

The error was caused by the change of the ffmpeg variable from representing the string to the program location to its own class. This issue can be fixed with one line.

```diff
-                   'ffmpeg_location': ffmpeg,
+                   'ffmpeg_location': ffmpeg.getPath(),
 ```

The new version will be pushed in a new release coming soon.

**Closed by WyattBlue** 2021-01-29 02:30 UTC
Labels: bug
