### ISSUE TITLE
Audio quality is degraded with auto-editor

### ISSUE THREAD

**Issue by Saya47** [WyattBlue/auto-editor#94] opened 2020-11-07 21:04 UTC
Hello! I've been using Auto Editor a lot but I suddenly noticed, all the audios are degraded by a lot, the quality is lost and the speech sounds robot like.

I use this command to edit my videos:

`auto-editor "input.mkv" --frame_margin 2 --video_speed 1 --silent_speed 999 -o "output.mp4" --no_open --cut_by_this_track 1 --video_codec libx264 --my_ffmpeg --audio_bitrate 192k`

These are OBS recordings, recording my laptop's screen and the sounds are 192 kbps.

So I compared the media info of the source files and auto-editor encoded files to find out why the quality is degraded:

![image](https://user-images.githubusercontent.com/35542834/98451320-dc7e4200-2159-11eb-8860-c4cbee1ef456.png)

And as you can see, auto-editor, has changed the audio codec and also lowered the bitrate, this is probably the reasons, but I'm not sure, what things can I test here to resolve the issue?

Thanks very much in advance for all the work.

**Comment by Saya47** [comment] 2020-11-08 13:33
So I realized the issue is that auto editor by default dowmixes all audio streams, and an audio stream getting mixed with 4 other empty audio streams causes the quality loss. so I used the --keep_tracks_seperate option but idk why at the stage where it wants to write the output file, it fails with this error:

`    Error! The file output.mp4 was not created!`


`auto-editor "input.mkv" --frame_margin 2 --video_speed 1 --silent_speed 999 -o "output.mp4" --no_open --cut_by_this_track 1 --video_codec libx264 --my_ffmpeg --audio_bitrate 192k --keep_tracks_seperate`

So I need a way for auto editor to generate more output for me.

And I wish there was a way to set audio_bitrate for the output anyway.

Thanks!

**Comment by Saya47** [comment] 2020-11-08 14:39
I know this got very long, so to summarize:

Auto-Editor has a bug with --keep_tracks_seperate:

`auto-editor "input.mp4" -o "output.mp4" --keep_tracks_seperate`
Error! The file output.mp4 was not created.

You can test this against any file.
Please note if you happen to already have a file named output.mp4 in your directory, you won't get the error, it will simply finish but actually doesn't "write" any data to the file.

**Comment by WyattBlue** [comment] 2020-11-08 16:52
Thanks for the report.

I'll try to get to the bottom of all these issues. Especially the `--keep_tracks_seperate` bug.

**Comment by WyattBlue** [comment] 2021-02-07 02:38
@Saya47 It's been a while, is this issue still happening, and if so, has anything changed?

**Comment by Saya47** [comment] 2021-02-09 13:01
Hello!
So I upgraded the program using pip (pip install -U auto-editor) and tried to test it but I got this error:

```
C:\Users\S\Downloads>auto-editor "2021-02-09 16-19-27.mkv" --frame_margin 2 --video_speed 1 --silent_speed 999 -o "2021-02-09 16-19-27.mp4" --no_open exportMediaOps --video_codec libx264 --audio_bitrate 192k --my_ffmpeg
Error while processing the decoded data for stream #4:0
Error! The file 2021-02-09 16-19-27.mp4 was not created.

This is not a normal error.
 This message will only show up if there's something definitely wrong with the program.
Create a bug report at:
  https://github.com/WyattBlue/auto-editor/issues/
```
I don't know why this is happening, I have no idea how to debug this or check if there are any logs.
Thanks.

**Comment by WyattBlue** [comment] 2021-02-09 17:10
@Saya47 , my guess is the conversion from the matroska container to the mp4 container is the cause of the error. (This will be something that will have to be tested going forward)

**Comment by Saya47** [comment] 2021-03-02 17:48
![report](https://user-images.githubusercontent.com/35542834/109690367-836c6b00-7b9b-11eb-8b5a-e6a5fcc6ffa8.PNG)
Hello. An issue I came across with is this.:
This video has two audio tracks, and this time around, I actually was not using the `--keep_tracks_seperate` option. I wanted auto-editor to downmix both audio tracks and do it's wonders like before!
But there seems to be a new bug: what it did was, it edited my file fine up until the 57 minute mark (the red marker on the picture), it sped up the silences just fine, but after the marker, the first audio track is silent but the second audio has sound as you can see, auto-editor treated the rest of the audio (the audio after 57 minute mark) as silence and sped up all of the second track. So basically auto-editor based the cuts on the first audio track only instead of downmixing like before. And in the output file, the part after 57 minute marker were sped up which made the teacher speak with 999 speed for the rest of the video.
Here's the command:
```
auto-editor "A1.mp4" -o "A2.mp4" --frame_margin 2 --video_speed 1 --silent_speed 999 --no_open --my_ffmpeg exportMediaOps --video_codec libx264
```
Thanks very much for reading <3

**Comment by WyattBlue** [comment] 2021-10-02 06:17
Closing because this issue is very old and may not be relevant to newer versions.

**Closed by WyattBlue** 2021-10-02 06:17 UTC
Labels: bug
